# Generated by Django 5.0.6 on 2024-07-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='text',
        ),
    ]
